#-------------------------------
# General Site Settings
title: Fantasy
logo: logo.svg # You can add own logo.
description: Not deep, just simple


#-------------------------------
# Author Settings
author:
  name: fantasy
  image: 01.jpg
  say-hello: Hello, I’m <strong>Fantasy</strong>
  bio: 喜欢胡思乱想，喜欢编程,机械，音乐和很多乱七八糟的事，喜欢接触和学习新的事物和技术，不求深刻，只求简单。<br></br></a>Love  &nbsp&nbsp&nbsp<a href="#">music</a> & <a href="#"><a href="#">making blind and disorderly conjectures</a></a>.


#-------------------------------
# Contact links
twitter: https://github.com/fantasywoc/fantasywoc.github.io/ # Add your Twitter handle
facebook: https://github.com/fantasywoc/fantasywoc.github.io/ # Add your Facebook handle
dribbble: https://fantasywoc.github.io/ # Add your Dribbble handle
i#nstagram: https://fantasywoc.github.io/ # Add your Instagram handle
#pinterest: https://fantasywoc.github.io/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
#disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
#google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
#mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
